export enum Category {
  ACTION = 'Action',
  ADVENTURE = 'Adventure',
  COMEDY = 'Comedy',
  SCI_FI = 'Sci-Fi',
  HORROR = 'Horror',
  DRAMA = 'Drama',
  ROMANCE = 'Romance',
  DOCUMENTARY = 'Documentary',
  ANIMATION = 'Animation',
  FAMILY = 'Family',
  FANTASY = 'Fantasy',
  THRILLER = 'Thriller',
  CRIME = 'Crime',
  MYSTERY = 'Mystery',
  WAR = 'War',
  HISTORY = 'History',
  MUSIC = 'Music',
  WESTERN = 'Western',
  BIOGRAPHY = 'Biography',
}
